# Generated by Django 4.2 on 2024-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledgerapp", "0002_remove_bookmodel_sumexpenses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="sumexpenses",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="sumincome",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
