# Generated by Django 4.2 on 2024-03-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledgerapp", "0003_bookmodel_sumexpenses_bookmodel_sumincome_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookmodel", name="sumexpenses",),
        migrations.RemoveField(model_name="bookmodel", name="sumincome",),
        migrations.RemoveField(model_name="bookmodel", name="total",),
    ]
