# Generated by Django 4.2 on 2024-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledgerapp", "0007_previousmonthdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="previousmonthdata",
            name="total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
