# Generated by Django 4.2 on 2024-03-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledgerapp", "0008_previousmonthdata_total"),
    ]

    operations = [
        migrations.RemoveField(model_name="previousmonthdata", name="month",),
    ]
